// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqd_1jh4vONUl24OeP80AFiP6x2xti3fg',
    appId: '1:1033795471116:web:d925eb37eafd7d06ddeb29',
    messagingSenderId: '1033795471116',
    projectId: 'cinetalk-fda66',
    authDomain: 'cinetalk-fda66.firebaseapp.com',
    storageBucket: 'cinetalk-fda66.firebasestorage.app',
    measurementId: 'G-Z8CSER406P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9Oe2M2VzbqHFuiBsXgr4vrW3GlNB4SNs',
    appId: '1:1033795471116:android:0b63f116759473aeddeb29',
    messagingSenderId: '1033795471116',
    projectId: 'cinetalk-fda66',
    storageBucket: 'cinetalk-fda66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbKt-t1SXGaiPu8WI9kMZLQsLNzYXzrDY',
    appId: '1:1033795471116:ios:13fa30915dbbe3acddeb29',
    messagingSenderId: '1033795471116',
    projectId: 'cinetalk-fda66',
    storageBucket: 'cinetalk-fda66.firebasestorage.app',
    iosBundleId: 'com.example.flutterForum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbKt-t1SXGaiPu8WI9kMZLQsLNzYXzrDY',
    appId: '1:1033795471116:ios:13fa30915dbbe3acddeb29',
    messagingSenderId: '1033795471116',
    projectId: 'cinetalk-fda66',
    storageBucket: 'cinetalk-fda66.firebasestorage.app',
    iosBundleId: 'com.example.flutterForum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqd_1jh4vONUl24OeP80AFiP6x2xti3fg',
    appId: '1:1033795471116:web:99a1f52517ab1b4fddeb29',
    messagingSenderId: '1033795471116',
    projectId: 'cinetalk-fda66',
    authDomain: 'cinetalk-fda66.firebaseapp.com',
    storageBucket: 'cinetalk-fda66.firebasestorage.app',
    measurementId: 'G-3MW36WK1SZ',
  );
}
